#!/bin/bash

notify() {
  notify-send -u low -t 1000 -a Volume "$1"
}

getCurrentVolume() {
  response=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
  echo $response
}

getMute() {
  response=$(pactl list sinks | grep [[:space:]]Mute:)
  echo $response
}

case "$1" in
  raise)
    for SINK in `pacmd list-sinks | grep 'index:' | cut -b12-`
    do
      pactl set-sink-volume $SINK +5%
    done
    notify "Volume increased"
    #notify "Current volume is: $(getCurrentVolume)"
    ;;
  lower)
    for SINK in `pacmd list-sinks | grep 'index:' | cut -b12-`
    do
      pactl set-sink-volume $SINK -5%
    done
    #notify "Current volume is: $(getCurrentVolume)"
    notify "Volume lowered"
    ;;
  mute)
    for SINK in `pacmd list-sinks | grep 'index:' | cut -b12-`
    do
      pactl set-sink-mute $SINK toggle
    done
    #notify "Current volume is: $(getMute)"
    notify "Volume mute"
    ;;
  mute-mic)
    for SINK in `pacmd list-sinks | grep 'index:' | cut -b12-`
    do
      pactl set-source-mute $SINK toggle
    done
    ;;
  *)
    echo "Usage: $0 {raise|lower}"
    exit 2
esac

exit 0
